//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MobileToolStoreEntities : DbContext
    {
        public MobileToolStoreEntities()
            : base("name=MobileToolStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblComentario> TblComentario { get; set; }
        public virtual DbSet<TblDetalleFactura> TblDetalleFactura { get; set; }
        public virtual DbSet<TblFacturas> TblFacturas { get; set; }
        public virtual DbSet<TblMarcas> TblMarcas { get; set; }
        public virtual DbSet<TblProductoMarca> TblProductoMarca { get; set; }
        public virtual DbSet<TblProductoProveedor> TblProductoProveedor { get; set; }
        public virtual DbSet<TblProductos> TblProductos { get; set; }
        public virtual DbSet<TblProveedores> TblProveedores { get; set; }
        public virtual DbSet<TblUsuarios> TblUsuarios { get; set; }
        public virtual DbSet<TblProductosMasVendidos> TblProductosMasVendidos { get; set; }
    }
}
