//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComentario
    {
        public int id { get; set; }
        public string nombreCompleto { get; set; }
        public string telefono { get; set; }
        public string correoElectronico { get; set; }
        public string mensaje { get; set; }
    }
}
