//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFacturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFacturas()
        {
            this.TblDetalleFactura = new HashSet<TblDetalleFactura>();
        }
    
        public int codigoFactura { get; set; }
        public string nombreCliente { get; set; }
        public System.DateTime fechaFacturacion { get; set; }
        public decimal totalPagar { get; set; }
        public string numeroTarjeta { get; set; }
        public System.DateTime fechaCaducidad { get; set; }
        public string codigoSeguridad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura { get; set; }
    }
}
