//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductoMarca
    {
        public int id { get; set; }
        public string codigoBarras { get; set; }
        public string codigoMarca { get; set; }
    
        public virtual TblMarcas TblMarcas { get; set; }
        public virtual TblProductos TblProductos { get; set; }
    }
}
