//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProductos()
        {
            this.TblProductoMarca = new HashSet<TblProductoMarca>();
            this.TblProductoProveedor = new HashSet<TblProductoProveedor>();
        }
    
        public string codigoBarras { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public string tipo { get; set; }
        public string modelo { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string disponibilidad { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductoMarca> TblProductoMarca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductoProveedor> TblProductoProveedor { get; set; }
    }
}
